# Generated by Django 4.2.7 on 2024-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_uploadedfile_processed_file_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='processed_file',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='default_file.geojson', upload_to='user_files/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
